export const CREATE_ANNOTATION = 'CREATE_ANNOTATION';
export const DELETE_ANNOTATION = 'DELETE_ANNOTATION';
export const EDIT_ANNOTATION = 'EDIT_ANNOTATION';
export const GET_ALL_ANNOTATIONS = 'GET_ALL_ANNOTATIONS';
